version: '3.3'
services:
  delikuki:
    image: postgres:13
    environment:
      - POSTGRES_DB=delikuki-db
      - POSTGRES_USER=jazzielp
      - POSTGRES_PASSWORD=Toluca01
    ports:
      - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    
  pgadmi:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
        - 5050:80